dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-dreamlte_eur_open_10.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-dream2lte_eur_open_10.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
